todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'
urlpatterns = [
    path('', views.index, name = 'index'),
    #from start -> this path -> views.index -> index.html
    path('<int:todo_id>', views.detail, name = 'detail'),
    #from index.html -> this path -> views.detail -> detail.html
    path('<int:todo_id>/check_complete/', views.checkComplete, name = 'check'),
    #from detail.html -> this path -> views.checkComplete -> index.html
    path('<int:todo_id>/editor/', views.adjust, name = 'adjust'),
    #from detail.html -> this path -> views.adjust -> adjust.html
    # ->views.adjust with POST -> adjustment.html
    path('<int:todo_id>/notice_for_deletion/', views.delete, name = 'delete'),
    #from detail.html -> this path -> views.deletion -> delete.html
    path('completed_list/', views.completedList, name = 'completed'),
    #from index.html -> this path -> views.finishedList ->finishedList.html
    path('register/', views.create, name = 'create'),
    #from index.html -> this path -> views.create -> create.html
    #-> views.create with POST -> creation.html


]

winter_project/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('todo.urls')),
    path('admin/', admin.site.urls),
]

todo/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class Todo(models.Model):
    todo_title = models.CharField(max_length = 50)
    due_date = models.DateTimeField(blank=True, null=True, default = 0)

    priority = models.IntegerField(validators=[MinValueValidator(0),], default = 5)
    text = models.TextField(blank=True, null=True)
    def __str__(self):
        return self.todo_title

class CompletedTodo(models.Model):
    todo_title = models.CharField(max_length = 50)
    due_date = models.DateTimeField(blank=True, null=True, default = 0)

    priority = models.IntegerField(validators=[MinValueValidator(0),], default = 5)
    text = models.TextField(blank=True, null=True)
    def __str__(self):
        return self.todo_title

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib import messages
from django.utils.timezone import datetime


from .models import Todo, CompletedTodo
from .form import PostForm



def index(request):
#This function has to give todo objects in todo LIST to index.html
#shows todo LIST in order of priority
    todoList = Todo.objects.order_by('priority')

    expiredList = Todo.objects.filter(due_date__lte = datetime.today())
    #At here, there is timezone problem, not haven't been solved yet
    context = {
        'todo_list':todoList,
        'expired_list': expiredList,
    }

    return render(request, 'todo/index.html', context)

def detail(request, todo_id):
#this function has to give id of todo object to detail.html
    try:
        todo =  Todo.objects.get(pk=todo_id)
    except Todo.DoesNotExist:
        raise Http404("Chosen Todo does not exist")
    return render(request, 'todo/detail.html', {'todo':todo})

def checkComplete(request, todo_id):
    #at here, generates completedTodo object having same information with givin todo object,
    #deletes the given todo object, and redirect to todo:index
    todo = get_object_or_404(Todo, pk=todo_id)
    completed = CompletedTodo()
    completed.todo_title = todo.todo_title
    completed.text = todo.text
    completed.priority = todo.priority
    completed.due_date = todo.due_date
    completed.save()
    todo.delete()

    return redirect('todo:index')

def adjust(request, todo_id):
#at this method, when request is not post, it renders adjust.html
#if request is post, adjusts new information with corresponding todo object
#and then renders adjustment.html with error code
    todo = get_object_or_404(Todo, pk=todo_id)
    if request.method == 'POST':
        form = PostForm(request.POST, instance = todo)
        #above code is 1st major difference between create function and adjust function
        if form.is_valid():
            todo = form.save()
            return render(request, 'todo/adjustment.html',{'error':0})
        else:
            return render(request, 'todo/adjustment.html', {'error':1})

    else:
        form = PostForm(instance = todo)
        #above code is 2nd major difference between create function and adjust function
        return render(request, 'todo/create.html', {'form': form})

def delete(request, todo_id):
    #delete the object corresponding to todo_id
    #and redirect todo:index
    todo = get_object_or_404(Todo,pk=todo_id)
    title = todo.todo_title
    todo.delete()
    return render(request, 'todo/deletion.html', {'title' : title})

def completedList(request):
#this function shows list of completedTodo objects in order of due_date
    completedList = CompletedTodo.objects.order_by('due_date')
    context = {
        'completed_list':completedList
    }

    return render(request, 'todo/completedList.html', context)

def create(request):
    #at this method, when request is not post, it renders creat.html
    #if request is post, generates form with information of request.POST,
    #with the form, generates object at DB,
    #and then renders creation.html with error code
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid() :
            todo = form.save(commit=False)
            todo.save()
            context = {
            'error_value' : 0
            }
            return render(request, 'todo/creation.html', context)

        else:
            context = {
            'error_value' : 1
            }
            return render(request, 'todo/creation.html', context)

    else:
        form = PostForm()
        return render(request, 'todo/create.html', {'form': form})

todo/templates/todo/adjustment.html
{% if error_value == 1 %}
  <p><strong>에러가 나서, 수정되지 않았습니다.</strong></p>
{% else %}
  <h1> 완료되었습니다 </h1>
{%endif%}

<form action = "{% url 'todo:index' %}">
  <input type = "submit" value="돌아가기">
</form>

todo/templates/todo/completedList.html
<h1> 완료된 리스트 </h1>


{% if completed_list %}
  <ul>
  {% for todo in completed_list %}
    <li>
      {{todo.todo_title}}/{{todo.due_date.year}}.
      {{todo.due_date.month}}.{{todo.due_date.day}}/
      priority:{{todo.priority}}
    </li>
  {% endfor %}
  </ul>
{% else %}
<h2> 완료한 일이 하나도 없음.. </h2>
{% endif %}


<form action = "{% url 'todo:index' %}">
  <input type = "submit" value="돌아가기">
</form>

todo/templates/todo/create.html
<h1> 새로운 TODO 등록 </h1>

<form method = 'POST' >
  {%csrf_token%} {{form.as_p}}
  <button type="submit"> 저장 </button>

<a href = "{% url 'todo:index' %}">돌아가기     </a>

todo/templates/todo/creation.html
{% if error_value == 1 %}
  <p><strong>에러가 나서, 등록되지 않았습니다.</strong></p>
{% else %}
  <h1> 완료되었습니다 </h1>
{%endif%}

<form action = "{% url 'todo:index' %}">
  <input type = "submit" value="돌아가기">
</form>

todo/templates/todo/deletion.html
<h1> 삭제되었습니다 </h1>
<h3> 삭제된 todo는 '{{title}}'  </h3>

<form action = "{% url 'todo:index'%}">
  <input type = "submit" value="돌아가기">
</form>

todo/templates/todo/detail.html
<h1>{{ todo.todo_title}} </h1>

<h3> 우선순위: {{todo.priority}} / 기한: {{todo.due_date.year}}.
  {{todo.due_date.month}}.{{todo.due_date.day}} </h3>
<div style ='border: 1px solid gold'>
  <p> {{todo.text}} </p>
</div>

<form action = "{% url 'todo:adjust' todo.id %}">
  <input type = "submit" value="수정하기">
</form>

<form action = "{% url 'todo:delete' todo.id %}">
  <input type = "submit" value="삭제하기">
</form>

<form action = "{% url 'todo:index' %}">
  <input type = "submit" value="돌아가기">
</form>

todo/templates/todo/finishedList.html
<h1> 완료된 리스트 </h1>


{% if finished_list %}
  <ul>
  {% for todo in finished_list %}
    <li>
      {{todo.todo_title}}/{{todo.due_date.year}}.
      {{todo.due_date.month}}.{{todo.due_date.day}}/
      priority:{{todo.priority}}
    </li>
  {% endfor %}
  </ul>
{% else %}
<h2> 완료한 일이 하나도 없음.. </h2>
{% endif %}


<form action = "{% url 'todo:index' %}">
  <input type = "submit" value="돌아가기">
</form>

todo/templates/todo/index.html
<h1> TODO LIST </h1>

<form action = "{% url 'todo:completed' %}">
  <input type = "submit" value="완료된 리스트">
</form>

<form action = "{% url 'todo:create' %}">
  <input type = "submit" value="새로운 todo 작성하기">
  </form>


{% if expired_list %}
<ul style="background-color:Tomato;"> <h3 style="bold">알림!</h3>

  {% for todo in expired_list %}
    <li>
    {{todo.todo_title}}/{{todo.due_date.year}}.
    {{todo.due_date.month}}.{{todo.due_date.day}}
    </li>
  {% endfor %}
  기한이 만료되었습니다.
  </ul>
  {% endif %}


{% if todo_list %}
  <ul>
    {% for todo in todo_list %}
      <li><a href="{% url 'todo:detail' todo.id %}">
        {{todo.todo_title}}/{{todo.due_date.year}}.
        {{todo.due_date.month}}.{{todo.due_date.day}}
        /priority:{{todo.priority}}</a>
        <form action = "{% url 'todo:check' todo.id %}">
          <input type = "submit" value="완료">
          </form>
      </li>

      {% endfor %}
  </ul>
{% else %}
  <h2>현재로서 할일 없음 </h2>
{% endif %}